"use client";

import { useState } from "react";
import { GlassCard } from "@/components/shared/glass-card";
import { Button } from "@/components/ui/button";
import { ShieldCheck, Smartphone, Key, Copy, Check, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";

export function MFASetup() {
  const [step, setStep] = useState(1);
  const [copied, setCopied] = useState(false);
  const [otp, setOtp] = useState("");

  const copySecret = () => {
    navigator.clipboard.writeText("JBSWY3DPEHPK3PXP");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-md mx-auto space-y-8">
      <div className="text-center space-y-2">
        <h2 className="text-3xl font-bold tracking-tight">Protect Your Account</h2>
        <p className="text-muted-foreground">Add an extra layer of security with Multi-Factor Authentication.</p>
      </div>

      <div className="flex justify-between items-center px-4 relative">
        <div className="absolute top-1/2 left-0 right-0 h-[1px] bg-white/10 -z-10" />
        {[1, 2, 3].map((s) => (
          <div 
            key={s} 
            className={cn(
              "w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold border transition-all duration-500",
              step === s ? "bg-primary border-primary text-white scale-110 shadow-[0_0_15px_rgba(var(--primary-rgb),0.5)]" : 
              step > s ? "bg-emerald-500 border-emerald-500 text-white" : "bg-black border-white/10 text-muted-foreground"
            )}
          >
            {step > s ? <Check className="w-4 h-4" /> : s}
          </div>
        ))}
      </div>

      <GlassCard className="p-8">
        {step === 1 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="p-4 bg-primary/10 rounded-2xl w-fit mx-auto">
              <Smartphone className="w-8 h-8 text-primary" />
            </div>
            <div className="text-center space-y-2">
              <h3 className="text-xl font-bold">Install Authenticator</h3>
              <p className="text-sm text-muted-foreground">
                Download Google Authenticator, Authy, or any TOTP-compatible app on your mobile device.
              </p>
            </div>
            <Button onClick={() => setStep(2)} className="w-full" variant="premium">
              I've installed the app <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500">
            <div className="text-center space-y-4">
              <h3 className="text-xl font-bold">Scan QR Code</h3>
              <div className="bg-white p-4 rounded-2xl w-48 h-48 mx-auto flex items-center justify-center border-4 border-primary/20">
                {/* Mock QR Code */}
                <div className="grid grid-cols-5 gap-1 w-full h-full opacity-80">
                  {[...Array(25)].map((_, i) => (
                    <div key={i} className={cn("rounded-sm", Math.random() > 0.5 ? "bg-black" : "bg-white")} />
                  ))}
                </div>
              </div>
              <p className="text-sm text-muted-foreground">
                Scan the QR code above or enter the secret key manually.
              </p>
            </div>
            
            <div className="bg-black/40 border border-white/10 p-3 rounded-xl flex items-center justify-between">
              <code className="text-xs font-mono text-primary">JBSW Y3DP EHPK 3PXP</code>
              <Button variant="ghost" size="sm" onClick={copySecret} className="h-8 px-2">
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
              </Button>
            </div>

            <Button onClick={() => setStep(3)} className="w-full" variant="premium">
              Next Step <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500">
            <div className="p-4 bg-primary/10 rounded-2xl w-fit mx-auto">
              <ShieldCheck className="w-8 h-8 text-primary" />
            </div>
            <div className="text-center space-y-2">
              <h3 className="text-xl font-bold">Verify Security</h3>
              <p className="text-sm text-muted-foreground">
                Enter the 6-digit code generated by your authenticator app to complete setup.
              </p>
            </div>
            
            <div className="flex justify-center gap-2">
              {[...Array(6)].map((_, i) => (
                <input
                  key={i}
                  type="text"
                  maxLength={1}
                  className="w-10 h-12 bg-white/5 border border-white/10 rounded-xl text-center text-xl font-bold focus:outline-none focus:ring-2 focus:ring-primary/50"
                  onChange={(e) => {
                    if (e.target.value && i < 5) {
                      (e.target.nextSibling as HTMLInputElement)?.focus();
                    }
                    setOtp(prev => prev + e.target.value);
                  }}
                />
              ))}
            </div>

            <Button onClick={() => alert("MFA Enabled!")} className="w-full" variant="premium">
              Enable MFA
            </Button>
          </div>
        )}
      </GlassCard>

      <p className="text-center text-xs text-muted-foreground">
        Need help? <a href="#" className="text-primary hover:underline">Contact Institutional Support</a>
      </p>
    </div>
  );
}
